<?php require '../app/templates/header.phtml'; ?>

<h1>Register</h1>
<form action="index.php?url=register" method="POST">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>

<?php require '../app/templates/footer.phtml'; ?>
